name: Generate Notes Metadata

on:
  push:
    branches:
      - main
    paths:
      - 'Notes/**'

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install @octokit/rest fs path
      
      - name: Generate and commit metadata file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/workflows/generate-notes-metadata.js
          
          # Stage the changes to the JSON file
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add notes_data.json
          git commit -m "feat(ci): Auto-generate notes metadata"
          
          # Push the changes to the repository
          git push
